apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090 
  isDefault: true
  access: proxy
  editable: true

- name: Loki
  type: loki
  url: http://loki:3100
  access: proxy
  editable: true

- name: Tempo
  type: tempo
  url: http://tempo:3200
  access: proxy
  editable: true

- name: Mimir
  type: prometheus
  url: http://mimir:9009
  access: proxy
  editable: true